<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Lightning Manager</Product>
    <Description>BTC Lightning management UI for stores using external backends or BTCPay Server's shared internal node.</Description>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemDefinitionGroup>
    <ProjectReference>
      <Properties>StaticWebAssetsEnabled=false</Properties>
      <Private>false</Private>
      <ExcludeAssets>runtime;native;build;buildTransitive;contentFiles</ExcludeAssets>
    </ProjectReference>
  </ItemDefinitionGroup>

  <ItemGroup>
    <ProjectReference Include="../submodules/btcpayserver/BTCPayServer/BTCPayServer.csproj" />
  </ItemGroup>
</Project>
